/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as SelfcareRouteImport } from './routes/selfcare'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as JewelleryRouteImport } from './routes/jewellery'
import { Route as DesignerClothesRouteImport } from './routes/designer-clothes'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ArtworksRouteImport } from './routes/artworks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutConfirmationOrderIdRouteImport } from './routes/checkout.confirmation.$orderId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfcareRoute = SelfcareRouteImport.update({
  id: '/selfcare',
  path: '/selfcare',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryRoute = JewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerClothesRoute = DesignerClothesRouteImport.update({
  id: '/designer-clothes',
  path: '/designer-clothes',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksRoute = ArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutConfirmationOrderIdRoute =
  CheckoutConfirmationOrderIdRouteImport.update({
    id: '/confirmation/$orderId',
    path: '/confirmation/$orderId',
    getParentRoute: () => CheckoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artworks': typeof ArtworksRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/craftsmanship': typeof CraftsmanshipRoute
  '/designer-clothes': typeof DesignerClothesRoute
  '/jewellery': typeof JewelleryRoute
  '/our-story': typeof OurStoryRoute
  '/perfumes': typeof PerfumesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/selfcare': typeof SelfcareRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/terms': typeof TermsRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artworks': typeof ArtworksRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/designer-clothes': typeof DesignerClothesRoute
  '/jewellery': typeof JewelleryRoute
  '/our-story': typeof OurStoryRoute
  '/perfumes': typeof PerfumesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/selfcare': typeof SelfcareRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/terms': typeof TermsRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artworks': typeof ArtworksRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/craftsmanship': typeof CraftsmanshipRoute
  '/designer-clothes': typeof DesignerClothesRoute
  '/jewellery': typeof JewelleryRoute
  '/our-story': typeof OurStoryRoute
  '/perfumes': typeof PerfumesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/selfcare': typeof SelfcareRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/terms': typeof TermsRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$slug': typeof ProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artworks'
    | '/checkout'
    | '/craftsmanship'
    | '/designer-clothes'
    | '/jewellery'
    | '/our-story'
    | '/perfumes'
    | '/privacy-policy'
    | '/selfcare'
    | '/shipping-returns'
    | '/terms'
    | '/checkout/payment'
    | '/product/$slug'
    | '/checkout/'
    | '/checkout/confirmation/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artworks'
    | '/craftsmanship'
    | '/designer-clothes'
    | '/jewellery'
    | '/our-story'
    | '/perfumes'
    | '/privacy-policy'
    | '/selfcare'
    | '/shipping-returns'
    | '/terms'
    | '/checkout/payment'
    | '/product/$slug'
    | '/checkout'
    | '/checkout/confirmation/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/artworks'
    | '/checkout'
    | '/craftsmanship'
    | '/designer-clothes'
    | '/jewellery'
    | '/our-story'
    | '/perfumes'
    | '/privacy-policy'
    | '/selfcare'
    | '/shipping-returns'
    | '/terms'
    | '/checkout/payment'
    | '/product/$slug'
    | '/checkout/'
    | '/checkout/confirmation/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtworksRoute: typeof ArtworksRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  DesignerClothesRoute: typeof DesignerClothesRoute
  JewelleryRoute: typeof JewelleryRoute
  OurStoryRoute: typeof OurStoryRoute
  PerfumesRoute: typeof PerfumesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SelfcareRoute: typeof SelfcareRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  TermsRoute: typeof TermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selfcare': {
      id: '/selfcare'
      path: '/selfcare'
      fullPath: '/selfcare'
      preLoaderRoute: typeof SelfcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery': {
      id: '/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof JewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-clothes': {
      id: '/designer-clothes'
      path: '/designer-clothes'
      fullPath: '/designer-clothes'
      preLoaderRoute: typeof DesignerClothesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks': {
      id: '/artworks'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof ArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/confirmation/$orderId': {
      id: '/checkout/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/checkout/confirmation/$orderId'
      preLoaderRoute: typeof CheckoutConfirmationOrderIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutConfirmationOrderIdRoute: typeof CheckoutConfirmationOrderIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutConfirmationOrderIdRoute: CheckoutConfirmationOrderIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtworksRoute: ArtworksRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CraftsmanshipRoute: CraftsmanshipRoute,
  DesignerClothesRoute: DesignerClothesRoute,
  JewelleryRoute: JewelleryRoute,
  OurStoryRoute: OurStoryRoute,
  PerfumesRoute: PerfumesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SelfcareRoute: SelfcareRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  TermsRoute: TermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
