/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountResetRouteImport } from './routes/account.reset'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountForgotRouteImport } from './routes/account.forgot'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as CheckoutConfirmationOrderIdRouteImport } from './routes/checkout.confirmation.$orderId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountResetRoute = AccountResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const AccountForgotRoute = AccountForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const CheckoutConfirmationOrderIdRoute =
  CheckoutConfirmationOrderIdRouteImport.update({
    id: '/confirmation/$orderId',
    path: '/confirmation/$orderId',
    getParentRoute: () => CheckoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset': typeof AccountResetRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset': typeof AccountResetRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset': typeof AccountResetRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/privacy-policy'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/account/addresses'
    | '/account/forgot'
    | '/account/login'
    | '/account/register'
    | '/account/reset'
    | '/account/wishlist'
    | '/checkout/payment'
    | '/product/$slug'
    | '/account/'
    | '/checkout/'
    | '/checkout/confirmation/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/contact'
    | '/privacy-policy'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/account/addresses'
    | '/account/forgot'
    | '/account/login'
    | '/account/register'
    | '/account/reset'
    | '/account/wishlist'
    | '/checkout/payment'
    | '/product/$slug'
    | '/account'
    | '/checkout'
    | '/checkout/confirmation/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/privacy-policy'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/account/addresses'
    | '/account/forgot'
    | '/account/login'
    | '/account/register'
    | '/account/reset'
    | '/account/wishlist'
    | '/checkout/payment'
    | '/product/$slug'
    | '/account/'
    | '/checkout/'
    | '/checkout/confirmation/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reset': {
      id: '/account/reset'
      path: '/reset'
      fullPath: '/account/reset'
      preLoaderRoute: typeof AccountResetRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/forgot': {
      id: '/account/forgot'
      path: '/forgot'
      fullPath: '/account/forgot'
      preLoaderRoute: typeof AccountForgotRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/checkout/confirmation/$orderId': {
      id: '/checkout/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/checkout/confirmation/$orderId'
      preLoaderRoute: typeof CheckoutConfirmationOrderIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountForgotRoute: typeof AccountForgotRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetRoute: typeof AccountResetRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountForgotRoute: AccountForgotRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetRoute: AccountResetRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutConfirmationOrderIdRoute: typeof CheckoutConfirmationOrderIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutConfirmationOrderIdRoute: CheckoutConfirmationOrderIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
